[theme]
# Accent color (buttons, active elements) → science magenta
primaryColor = "#1f77b4"

# Main content background → deep lab dark blue
backgroundColor = "#ffffff"

# Sidebar & widgets → darker teal for separation
secondaryBackgroundColor = "#f0f2f6"

# Text color → near white for good contrast
textColor = "#262730"

# Font: clean, modern (you can switch to "serif" if you want a research-paper vibe)
font = "sans serif"
